[workspace]
resolver = "3"
members = [
    "crates/vrp-gpu",
    "crates/vrp-gpu-bench",
    "crates/vrp-gpu-cli",
]
exclude = ["crates/vrp-gpu-kernel"]

[workspace.package]
version = "0.1.1-alpha"
edition = "2024"
rust-version = "1.88"
authors = ["Guilherme Pedroza"]
license = "Apache-2.0"
repository = "https://github.com/pedrozaz/vrp-gpu"

[workspace.dependencies]
vrp-gpu = { version = "0.1.1-alpha", path = "crates/vrp-gpu" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"
