[graph]
targets = []

[advisories]
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8
unused-allowed-license = "allow"
allow = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
