[package]
name = "vrp-kernel"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Guilherme Pedroza"]
repository = "https://github.com/pedrozaz/vrp-gpu"
publish = false
description = "Dev-only crate for compiling batch 2-opt evaluation PTX kernels via cuda-oxide"

[workspace]
resolver = "3"

[dependencies]
cuda-device = { git = "https://github.com/NVLabs/cuda-oxide.git", rev = "1c0b81a52ea6af836c10e0f9820302828e1b57bb" }
